const marvelMovies = [
    // Phase 1
    { title: "Captain America: The First Avenger", year: 2011, phase: 1, rating: 6.9, director: "Joe Johnston", trailer: "https://youtu.be/W4DlMggBPvc?si=SaNtv8gOxNXdxQCl", description: "After being deemed unfit for military service, Steve Rogers volunteers for a top-secret research project that turns him into Captain America. Captain America is a 2011 superhero film based on the Marvel Comics character Captain America. Directed by Joe Johnston and starring Chris Evans as Steve Rogers. The film was released on July 22, 2011.", poster: "images/captainamericathefirstavenger.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=15j2-8vYQ0UtIokA77H1GNSFMQMSnxPtV&export=download&authuser=0&confirm=t&uuid=42a2e0a0-a217-4642-8bed-9b2a3a153c55&at=AGN2oQ312nQj6sscMo_l-LaacAK2:1773727782758", "1080p": "https://drive.usercontent.google.com/download?id=1egrxHDKwZ7UCWnOXor5rtWtYpqNJwOua&export=download&authuser=0&confirm=t&uuid=95cf1bd1-13b3-49c8-9af9-a9ec2081ea54&at=AGN2oQ0YWz-KBBl3mrg7hGhrHnrO%3A1773727851159", "4k": "https://drive.usercontent.google.com/download?id=1qglb86KW4s6UqAaHsqpGpf7EI1G4uYi8&export=download&authuser=0&confirm=t&uuid=94960ae3-c2b9-4529-86c8-92eb05093a86&at=AGN2oQ3BLYkJkZnhz6Yd24byGkTn%3A1773727859047" } },
    { title: "Captain Marvel", year: 2019, phase: 1, rating: 6.8, director: "Anna Boden, Ryan Fleck", trailer: "https://youtu.be/Z1BCujX3pw8?si=JV0R_8DvBLKb0CDS", description: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Captain Marvel is a 2019 superhero film based on the Marvel Comics character Captain Marvel. Directed by Anna Boden and Ryan Fleck and starring Brie Larson. The film was released on March 8, 2019.", poster: "images/captainmarvel.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Iron Man", year: 2008, phase: 1, rating: 7.9, director: "Jon Favreau", trailer: "https://youtu.be/8ugaeA-nMTc?si=Oo5iEgdBiim_L9J1", description: "After surviving an unexpected attack in enemy territory, jet-setting industrialist Tony Stark builds a high-tech suit of armor and vows to protect the world. Iron Man is a 2008 superhero film based on the Marvel Comics character Iron Man. Directed by Jon Favreau and starring Robert Downey Jr. The film was released on May 2, 2008.", poster: "images/ironman.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=19WGryUv1ewInGVPpehtuMvEXvuqNlbMX&export=download&authuser=0&confirm=t&uuid=38e2bf1d-5dcf-4afc-8029-6abce9bb1d2e&at=AGN2oQ15nAL_EfCFoJ-DDRJOe0db%3A1773727241990", "1080p": "https://drive.usercontent.google.com/download?id=1uIUeK3SbY7ZfJIoN16Z2v2UayVTi_m8S&export=download&authuser=0&confirm=t&uuid=6d287646-e28f-440a-9ec5-56c9f31e8597&at=AGN2oQ3kecwMKliD5aGYO85DUC8W%3A1773727365801", "4k": "https://drive.usercontent.google.com/download?id=128EH0YtdXNaWkQpCkNLj1hEV5Oo903bF&export=download&authuser=0&confirm=t&uuid=b8a4b1fc-58b6-4e2b-9304-57694b871b6f&at=AGN2oQ2z3dD4_vaeRPUl1i_-Uzg3%3A1773727415948" } },
    { title: "The Incredible Hulk", year: 2008, phase: 1, rating: 6.6, director: "Louis Leterrier", trailer: "https://youtu.be/xbqNb2PFKKA?si=DF99RQWuuaqEbNLJ", description: "Bruce Banner faces a nightmarish enemy after he is forced out of hiding. The Incredible Hulk is a 2008 superhero film based on the Marvel Comics character Hulk. Directed by Louis Leterrier and starring Edward Norton. The film was released on May 2, 2008, in the United States.", poster: "images/theincrediblehulk.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1kh32yCk5cynKrRGQMujsH962L3ez9DAy&export=download&authuser=0&confirm=t&uuid=08481100-d3b0-4466-8b97-d6c1f7dde6b0&at=AGN2oQ1XGbjkNuXcDmfl3QqA2oLh%3A1773727463015", "1080p": "https://drive.usercontent.google.com/download?id=1A3BzkzqIoz6qbUnx49cNz4rdkVOL2ouM&export=download&authuser=0&confirm=t&uuid=05b89efa-3389-4870-9649-d87a7daa6530&at=AGN2oQ0Wks9H63rZhP9PqrQDNRij%3A1773727529759", "4k": "" } },
    { title: "Iron Man 2", year: 2010, phase: 1, rating: 6.9, director: "Jon Favreau", trailer: "https://youtu.be/qsRZghNciIo?si=dmiz8w3RYa7AcWes", description: "Tony Stark is under pressure from various sources, to share his technology with the world. And, he needs to find a way to deal with his enemies Iron Man 2 is a 2010 superhero film based on the Marvel Comics character Iron Man. Directed by Jon Favreau and starring Robert Downey Jr. The film was released on May 7, 2010.", poster: "images/ironman2.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1VGycSVt3bqg0rhq5fywFbStbcXVvfkxS&export=download&authuser=0&confirm=t&uuid=e5fe4a17-8fdd-48e8-a94a-3d4735e06b72&at=AGN2oQ3CGkzvspyuOoQHo0cFgiFW%3A1773727585982", "1080p": "https://drive.usercontent.google.com/download?id=1PH71jLEKI7oEE-X-BtE07FNhoMuPotof&export=download&authuser=0&confirm=t&uuid=ca4ae2d0-cef2-4210-a3e6-f2a30afb4f72&at=AGN2oQ1BckooGAh3FxDuXGy5m-Qe%3A1773727645108", "4k": "https://drive.usercontent.google.com/download?id=1kRi5s-qdsOaqG2bnAAza-La0xq7ERhwm&export=download&authuser=0&confirm=t&uuid=a5ca1828-c058-4521-a711-686755974277&at=AGN2oQ0fSvolby7HWnoqJrZ0afCb%3A1773727676543" } },
    { title: "Thor", year: 2011, phase: 1, rating: 7.0, director: "Kenneth Branagh", trailer: "https://youtu.be/JOddp-nlNvQ?si=rBujNVZdjeSmZ8JN", description: "The powerful, but arrogant god Thor, is cast out of Asgard to live amongst humans on Earth, where he soon becomes one of their finest defenders. Thor is a 2011 superhero film based on the Marvel Comics character Thor. Directed by Kenneth Branagh and starring Chris Hemsworth, it is the first film in the Thor film series. The film was released on May 6, 2011.", poster: "images/thor.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1uLZBVSmYc91-NRkFCOFFqYXqdl_q9vuP&export=download&authuser=0&confirm=t&uuid=72debf46-d843-4132-9323-0d864926b462&at=AGN2oQ1nmC4gSB6bsT6RwZj7wN-i%3A1773727934097", "1080p": "https://drive.usercontent.google.com/download?id=1hYgo4-EBoiD5k8edgXZGYYjRw8ryaHle&export=download&authuser=0&confirm=t&uuid=74d236a4-0f6c-4efc-acf5-bc995994f4f9&at=AGN2oQ17Eb3jcFVzpO-d9f3Dvkvp%3A1773727946156", "4k": "https://drive.usercontent.google.com/download?id=1IgTgLKCw4Og-JSChIE0LzfHi2utmwAkq&export=download&authuser=0&confirm=t&uuid=b23087e0-4715-4fcb-a804-da9e3985f43c&at=AGN2oQ032_jLVwuxfIFSf4RYx0rs%3A1773728077563" } },
    { title: "The Avengers", year: 2012, phase: 1, rating: 8.0, director: "Joss Whedon", trailer: "https://youtu.be/eOrNdBpGMv8?si=DjYneUzdTN-__E-C", description: "Nick Fury of S.H.I.E.L.D. assembles a team of superheroes to stop Loki and his alien army from conquering Earth. The Avengers is a 2012 superhero film based on the Marvel Comics character Avengers. Directed by Joss Whedon. The film was released on May 4, 2012.", poster: "images/theavengers.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1KUVLrJAIQD37k9O62hP0hIx5IKLrb2BM&export=download&authuser=0&confirm=t&uuid=390b6923-4a18-478b-9a3d-32faedc46e8f&at=AGN2oQ20tUi_fF7FlGdaHAhhl4LA%3A1773727106173", "1080p": "https://drive.usercontent.google.com/download?id=1JXADzAC5CpaflVLeKi_NvwBke3vwEIJd&export=download&authuser=0&confirm=t&uuid=1cb0899d-61b3-4a28-bd10-a15eedaad9e2&at=AGN2oQ2Gblx9VVt8aktrTIJopDGj%3A1773727031318", "4k": "https://drive.usercontent.google.com/download?id=1R5cGwkgCJrL7ZZXLjGPO9e4sYMmmD_cO&export=download&authuser=0&confirm=t&uuid=e32a02ae-2158-46d9-82cb-99516d3a9289&at=AGN2oQ2nqAKfGPxpovV3vU_BCtnc%3A1773726900423" } },

    // Phase 2
    { title: "Iron Man 3", year: 2013, phase: 2, rating: 7.1, director: "Shane Black", trailer: "https://youtu.be/YLorLVa95Xo?si=KRNOOKRr6U_DKzrf", description: "When Tony Stark/Iron Man finds his world reduced to rubble, one question haunts him: Does the man make the suit, or does the suit make the man? Iron Man 3 is a 2013 superhero film based on the Marvel Comics character Iron Man. Directed by Shane Black and starring Robert Downey Jr. The film was released on May 3, 2013.", poster: "images/ironman3.jpg", links: { "720p": "", "1080p": "https://drive.usercontent.google.com/download?id=1BkYH068oBDhKHNfbuuaYlaW0eOm_MX_W&export=download&authuser=0&confirm=t&uuid=df12dc9b-b8ca-4639-afb3-b42c740b5c96&at=AGN2oQ3180RimcBL-hE_IjYbeKrb:1773728232836", "4k": "https://drive.usercontent.google.com/download?id=1RJ_Jtz7pJMuhn2HLseZAGe5tWFX4uMpp&export=download&authuser=0&confirm=t&uuid=02ec2669-a345-4593-9aee-864a7b2f7376&at=AGN2oQ2IBUEPWrgniRm8x7hb65BN:1773728296538" } },
    { title: "Thor: The Dark World", year: 2013, phase: 2, rating: 6.8, director: "Alan Taylor", trailer: "https://youtu.be/npvJ9FTgZbM?si=Q8ONdTgfc92pUi6y", description: "Thor fights to restore order across the cosmos...but an ancient race led by the vengeful Malekith returns to plunge the universe back into the darkness. Thor: The Dark World is a superhero film based on the Marvel Comics character Thor. Directed by Alan Taylor and starring Chris Hemsworth. The film was released on November 8, 2013.", poster: "images/thorthedarkworld.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1UVFNXbvVK38P0sYt-AErnK1rDv5o_ajK&export=download&authuser=0&confirm=t&uuid=b18cb263-45b8-455a-83a8-0a6f7bf2c76c&at=AGN2oQ0flbDwBLr15q7JffqKekPN:1773728335228", "1080p": "https://drive.usercontent.google.com/download?id=1QvU7KHB-OhVq1zsBkpgpfXRFnK_YWyWy&export=download&authuser=0&confirm=t&uuid=1b22b5fc-3d21-4204-8b1c-e1e35f031fde&at=AGN2oQ3svmUjiFRJ8yzIEL5tYyej:1773728336871", "4k": "https://drive.usercontent.google.com/download?id=1PVN0mQ9bvuPvW1hlhJ4w05u69p2Ab4ci&export=download&authuser=0&confirm=t&uuid=4b8a9ecc-78ae-4460-9f79-6b2c987e56f7&at=AGN2oQ2bLYrPhgWAx82u12TwpWlT:1773728341372" } },
    { title: "Captain America: The Winter Soldier", year: 2014, phase: 2, rating: 7.8, director: "Anthony Russo, Joe Russo", trailer: "https://youtu.be/7SlILk2WMTI?si=3vYlE69E8q8s9tG_", description: "Steve Rogers teams up with Natasha Romanoff, aka Black Widow, to battle a powerfull yet shadowy enemy in present-day Washington, D.C. The Winter Soldier. Captain America: The Winter Soldier is a 2014 superhero film based on the Marvel Comics character Captain America. Directed by Anthony and Joe Russo and starring Chris Evans. The film was released on April 4, 2014.", poster: "images/captainamericathewintersoldier.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1PiP-vqzQ-o99njBn1GnAL8Sf6tdPpgl7&export=download&authuser=0&confirm=t&uuid=42f9f3e2-d3c6-4150-a308-018d0f43c459&at=AGN2oQ0IaiK2VcI2H6qjIs4UInBn:1773728961329", "1080p": "https://drive.usercontent.google.com/download?id=1-_xuGJiyrbVZDltDkXjW7wSIuHzDHovw&export=download&authuser=0&confirm=t&uuid=5a38a0ac-a969-4a49-9527-f7bfdc8d50a2&at=AGN2oQ1T-lExkBZPCWNDtZH5Uz8R:1773728959846", "4k": "https://drive.usercontent.google.com/download?id=1eD6G6cjqoI3QikrBBBbWFGgD9yFhBHLl&export=download&authuser=0&confirm=t&uuid=ef815442-22e6-48b8-865d-bba97723f29d&at=AGN2oQ2nRAXEQ9QhGbxmhNSVj7eg:1773728962772" } },
    { title: "Guardians of the Galaxy", year: 2014, phase: 2, rating: 8.0, director: "James Gunn", trailer: "https://youtu.be/d96cjJhvlMA?si=GgwolXMjI1OB9vkZ", description: "Brash adventure Peter Quill finds himself the object of an unrelenting bounty hunt after stealing a mysterious orb coveted by a powerfull villian. Directed by James Gunn and starring Chris Pratt, Zoe Saldana, and Dave Bautista, it is the first film in the Guardians of the Galaxy series. This film was released on August 1, 2014.", poster: "images/guardiansofthegalaxy.jpg", links: { "720p": "https://drive.usercontent.google.com/download?id=1sk1M7krVbB278sVanKW0Hc-tSH65jcMT&export=download&authuser=0&confirm=t&uuid=83118299-ee22-45d1-aa23-3a5bec95a484&at=AGN2oQ1QIQaxZ-MKVKYHz67bI6MU:1773728451991", "1080p": "https://drive.usercontent.google.com/download?id=1SU9eN6bjUS6oTNSxmQXr01Pvd0i2Rivy&export=download&authuser=0&confirm=t&uuid=c51b5977-af64-4788-8d88-463da6f390a1&at=AGN2oQ1P9Uw-u-VcgDARb-QvxAzh:1773728453419", "4k": "https://drive.usercontent.google.com/download?id=15ROunu9_Hqrqzx1Aw9j8vAh767qNt2J9&export=download&authuser=0&confirm=t&uuid=e9227df0-e528-4ea2-b14d-6d0f80cfb5a9&at=AGN2oQ3OkYU3GzK5boOTbj7elQ7q:1773728454946" } },
    { title: "Avengers: Age of Ultron", year: 2015, phase: 2, rating: 7.3, director: "Joss Whedon", trailer: "https://youtu.be/JAUoeqvedMo?si=6_IuhmWB7Qse9D7w", description: "Tony Stark builds an AI system named Ultron, and when things go wrong, it's up to the Earth's mightiest heroes to stop the villian from enacting his terrible plan. Avengers: Age of Ultron is a 2015 superhero film based on the Marvel Comics character Avengers. Directed by Joss Whedon and starring Chris Hemsworth, it is the second film in the Avengers film series. The film premiered was released on May 1, 2015.", poster: "images/avengersageofultron.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Ant-Man", year: 2015, phase: 2, rating: 7.3, director: "Peyton Reed", trailer: "https://youtu.be/pWdKf3MneyI?si=VVrBf3Rh1_w4nsai", description: "Cat burglar Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world. Directed by Peyton Reed, starring Paul Rudd. This film was released on July 17, 2015.", poster: "images/ant-man.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Captain America: Civil War", year: 2016, phase: 2, rating: 7.8, trailer: "https://youtu.be/dKrVegVI0Us?si=xPzoKuNCQ08hBtLU", director: "Anthony Russo, Joe Russo", description: "The goverment's decision to push a hero Registration Act to regulate heroes creates a rift among the Avengers and the other heroes. Directed by Russo Brothers, starring Chris Evans and Robert Downey Jr. This film was released on May 6, 2016.", poster: "images/captainamericacivilwar.jpg", links: { "720p": "", "1080p": "", "4k": "" } },

    // Phase 3
    { title: "Doctor Strange", year: 2016, phase: 3, rating: 7.5, director: "Scott Derrickson", trailer: "https://youtu.be/HSzx-zryEgM?si=KnzZ5XjjH96qorPL", description: "Dr. Strange faces a difficulty choice of whether to return to his life of luxury or to protect the world as the most powerfull sorcerer in existence. Directed by Scott Derrickson, starring Benedict Cumberbatch. This film was released on November 4, 2016.", poster: "images/doctorstrange.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Guardians of the Galaxy Vol. 2", year: 2017, phase: 3, rating: 7.6, director: "James Gunn", trailer: "https://youtu.be/wUn05hdkhjM?si=SHxOlCQ9OvUn10bq", description: "Marvel Studios' Guadians of the Galaxy Vol. 2 continues the team's adventures as they unravel the mystery of Star-Lord's parentage. Directed by James Gunn, starring Chris Pratt, Zoe Saldana, and Dave Bautista. This film was released on May 5, 2017.", poster: "images/guardiansofthegalaxyvol.2.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Spider-Man: Homecoming", year: 2017, phase: 3, rating: 7.4, director: "Jon Watts", trailer: "https://youtu.be/U0D3AOldjMU?si=Msb32OatKe2ozwpR", description: "Peter Parker tries to stop Adrian 'The Vulture' Toomes from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student. Directed by Jon Watts, starring Tom Holland. This film was released on July 7, 2017.", poster: "images/spider-manhomecoming.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Thor: Ragnarok", year: 2017, phase: 3, rating: 7.9, director: "Taika Waititi", trailer: "https://youtu.be/ue80QwXMRHg?si=qtQT8RGyP6Aiu9-H", description: "Deprived of his mighty hammer Mjolnir, Thor must escape the other side of the universe to save his home, Asgard, from Hela, the goddess of Death. Directed by Taika Waititi and starring Chris Hemsworth. The film was released on May 3, 2017.", poster: "images/thorragnarok.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Black Panther", year: 2018, phase: 3, rating: 7.3, director: "Ryan Coogler", trailer: "https://youtu.be/xjDjIWPwcPU?si=P6-TwcKZyord8tQP", description: "T'Challa heir to the hidden kingdom of Wakanda, must lead his people into a new feature and confront a challenger from his country's past. Directed by Ryan Coogler, starring Chadwick Boseman and Michael B. Jordan. This film was released on February 16, 2018.", poster: "images/blackpanther.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Avengers: Infinity War", year: 2018, phase: 3, rating: 9.4, director: "Anthony Russo, Joe Russo", trailer: "https://youtu.be/6ZfuNTqbHE8?si=ZOq1EU0hyMyLFIpc", description: "With the powerfull Thanos on the verge of raining destruction upon the universe, the Avengers risk everything in the ultimate showdown of all time. Directed by Russo Brothers, starring Robert Downey Jr., Chris Evans, and Chris Hemsworth. This film was released on April 27, 2018.", poster: "images/avengersinfinitywar.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Ant-Man and the Wasp", year: 2018, phase: 3, rating: 7.0, director: "Peyton Reed", trailer: "https://youtu.be/UUkn-enk2RU?si=FFT7gDnmGhqrAiws", description: "Accompanied by Hope Van Dyne and Dr. Hank Pym, Scott Lang must once again don the Ant-Man suit and fight alongside the Wasp. Directed by Peyton Reed and starring Paul Rudd. The film was released on July 6, 2018.", poster: "images/ant-manthewasp.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Avengers: Endgame", year: 2019, phase: 3, rating: 9.8, director: "Anthony Russo, Joe Russo", trailer: "https://youtu.be/TcMBFSGVi1c?si=lTKUVuFxi9IZZlB5", description: "After the devastating events of Avengers: Infinity War, the Avengers Assembles once more to reverse thanos' actions and restore balance to the universe. Directed by Russo Brothers, starring Robert Downey Jr., Chris Evans, and Mark Ruffalo. This film was released on April 26, 2019", poster: "images/avengersendgame.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Spider-Man: Far From Home", year: 2019, phase: 3, rating: 7.4, director: "Jon Watts", trailer: "https://youtu.be/LFoz8ZJWmPs?si=__vdn0RolZV7XkvE", description: "Following the events of Avengers: Endgame, Spider-Man must step up to take on new threats in a world that has changed forever. Directed by Jon Watts and starring Tom Holland. The film was released on July 2, 2019.", poster: "images/spider-manfarfromhome.jpg", links: { "720p": "", "1080p": "", "4k": "" } },

    // Phase 4
    { title: "Black Widow", year: 2021, phase: 4, rating: 6.7, director: "Cate Shortland", trailer: "https://youtu.be/ybji16u608U?si=yYVYMuQBHH87XZns", description: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past airses. Directed by Cate Shortland, starring Scarlett Johansson. This film was released on July 9, 2021.", poster: "images/blackwidow.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, phase: 4, rating: 7.4, trailer: "https://youtu.be/8YjFbMbfXaQ?si=kNLa8pQNIUnbJ_uq", director: "Destin Daniel Cretton", description: "Shang-Chi, a martial arts master, must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization. Directed by Destin Daniel Cretton, starring Simu Liu. This film was released on September 3, 2021.", poster: "images/shangchi.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Eternals", year: 2021, phase: 4, rating: 6.8, director: "Chloé Zhao", trailer: "https://youtu.be/x_me3xsvDgk?si=B2ueVcM5cae9A1iW", description: "The Eternals are a group of ancient aliens who have been living on Earth in secret for thousands of years. When their ancient enemy, the Deviants, re-emerge, the Eternals must reunite to protect humanity. Directed by Chloé Zhao. The film was released on November 5, 2021.", poster: "images/eternals.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Spider-Man: No Way Home", year: 2021, phase: 4, rating: 8.2, director: "Jon Watts", trailer: "https://youtu.be/ZYzbalQ6Lg8?si=qqHvACACoqoaLmqE", description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear. Starring Tom Holland, Zendaya, and Benedict Cumberbatch.", poster: "images/spider-mannowayhome.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Doctor Strange in the Multiverse of Madness", year: 2022, phase: 4, rating: 6.9, director: "Sam Raimi", trailer: "https://youtu.be/aWzlQ2N6qqg?si=vHIND8b9o6M4NGMe", description: "Doctor Strange in the Multiverse of Madness is a 2022 superhero film based on the Marvel Comics character Doctor Strange. Directed by Sam Raimi and starring Chris Hemsworth, it is the second film in the Doctor Strange film series. The film premiered on May 1, 2022, and was released on May 1, 2022, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/doctorstrangeinthemultiverseofmadness.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Thor: Love and Thunder", year: 2022, phase: 4, rating: 6.2, director: "Taika Waititi", trailer: "https://youtu.be/Go8nTmfrQd8?si=ayJ59yEzb94ZZQP0", description: "Thor: Love and Thunder is a 2022 superhero film based on the Marvel Comics character Thor. Directed by Taika Waititi and starring Chris Hemsworth, it is the second film in the Thor film series. The film premiered on May 1, 2022, and was released on May 1, 2022, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/thorloveandthunder.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Black Panther: Wakanda Forever", year: 2022, phase: 4, rating: 7.0, director: "Ryan Coogler", trailer: "https://youtu.be/_Z3QKkl1WyM?si=Cl2eGk6YU7iH6w-E", description: "Black Panther: Wakanda Forever is a 2022 superhero film based on the Marvel Comics character Black Panther. Directed by Ryan Coogler and starring Chris Hemsworth, it is the second film in the Black Panther film series. The film premiered on May 1, 2022, and was released on May 1, 2022, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/blackpantherwakandaforever.jpg", links: { "720p": "", "1080p": "", "4k": "" } },

    // Phase 5
    { title: "Ant-Man and the Wasp: Quantumania", year: 2023, phase: 5, rating: 6.1, director: "Peyton Reed", trailer: "https://youtu.be/ZlNFpri-Y40?si=sX05sWAqB1FRxzbB", description: "Ant-Man and the Wasp: Quantumania is a 2023 superhero film based on the Marvel Comics character Ant-Man. Directed by Peyton Reed and starring Chris Hemsworth, it is the second film in the Ant-Man film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/antmanandthewaspquantumania.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Guardians of the Galaxy Vol. 3", year: 2023, phase: 5, rating: 7.9, director: "James Gunn", trailer: "https://youtu.be/u3V5KDHRQvk?si=_pArP3DNeua5MFnG", description: "Guardians of the Galaxy Vol. 3 is a 2023 superhero film based on the Marvel Comics character Guardians of the Galaxy. Directed by James Gunn and starring Chris Hemsworth, it is the second film in the Guardians of the Galaxy film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/guardiansofthegalaxyvolume3.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "The Marvels", year: 2023, phase: 5, rating: 6.0, director: "Chloé Zhao", trailer: "https://youtu.be/wS_qbDztgVY?si=OukYkbTDIPdpF_00", description: "The Marvels is a 2023 superhero film based on the Marvel Comics character The Marvels. Directed by Chloé Zhao and starring Chris Hemsworth, it is the second film in the The Marvels film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/themarvels.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Deadpool & Wolverine", year: 2024, phase: 5, rating: 7.7, director: "Shawn Levy", trailer: "https://youtu.be/73_1biulkYk?si=T74UQO3dPykWcZvJ", description: "Wolverine is recovering from his injuries when he crosses paths with the loudmouth Deadpool. They team up to defeat a common enemy. Starring Ryan Reynolds and Hugh Jackman.", poster: "images/deadpoolandwolverine.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Captain America: Brave New World", year: 2025, phase: 5, rating: 6.3, director: "Antony Hopkins", trailer: "https://youtu.be/1pHDWnXmK7Y?si=_ZjMdTdSCzWBi3t8", description: "Captain America: Brave New World is a 2025 superhero film based on the Marvel Comics character Captain America. Directed by Antony Hopkins and starring Chris Hemsworth, it is the second film in the Captain America film series. The film premiered on May 1, 2025, and was released on May 1, 2025, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/captainamericabravenewworld.jpg", links: { "720p": "", "1080p": "", "4k": "" } }
];

const dcMovies = [
    { title: "Man of Steel", year: 2013, director: " Zack Snyder", rating: 7.1, trailer: "https://youtu.be/T6DJcgm3wNY?si=xUmuLV6-ye9iD2fw", description: "An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened when other survivors of his home planet invade Earth. Starring Henry Cavill and Amy Adams.", poster: "images/manofsteel.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Batman v Superman: Dawn of Justice", year: 2016, director: "Zack Snyder", trailer: "https://youtu.be/0WWzgGyAH6Y?si=Ks1pUrEvYy6iTE-4", rating: 6.5, description: "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs. Starring Ben Affleck and Henry Cavill.", poster: "images/BatmanvsSuperman.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Suicide Squad", year: 2016, director: "David Ayer", rating: 5.9, trailer: "https://youtu.be/CmRih_VtVAs?si=nojrxrXc_Woi64U8", description: "Suicide Squad is a 2016 superhero film based on the DC Comics character Suicide Squad. Directed by David Ayer and starring Chris Hemsworth, it is the second film in the Suicide Squad film series. The film premiered on May 1, 2016, and was released on May 1, 2016, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/suicidesquad.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Wonder Woman", year: 2017, director: " Patty Jenkins", rating: 7.4, trailer: "https://youtu.be/VSB4wGIdDwo?si=YQTSwx4YzCO7AEBJ", description: "Wonder Woman is a 2017 superhero film based on the DC Comics character Wonder Woman. Directed by Patty Jenkins and starring Chris Hemsworth, it is the second film in the Wonder Woman film series. The film premiered on May 1, 2017, and was released on May 1, 2017, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/wonderwoman.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Justice League", year: 2017, director: " Zack Snyder", rating: 6.1, trailer: "https://youtu.be/3cxixDgHUYw?si=Xr5W0qid25jXUBli", description: "Justice League is a 2017 superhero film based on the DC Comics character Justice League. Directed by Zack Snyder and starring Chris Hemsworth, it is the second film in the Justice League film series. The film premiered on May 1, 2017, and was released on May 1, 2017, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/justiceleague.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Aquaman", year: 2018, director: " James Wan", rating: 6.8, trailer: "https://youtu.be/2wcj6SrX4zw?si=LAXspn9ClAckXkhK", description: "Aquaman is a 2018 superhero film based on the DC Comics character Aquaman. Directed by James Wan and starring Chris Hemsworth, it is the second film in the Aquaman film series. The film premiered on May 1, 2018, and was released on May 1, 2018, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/aquaman(2018).jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Shazam!", year: 2019, director: "David F. Sandberg", rating: 7.0, trailer: "https://youtu.be/s98AgxZw1Ek?si=JheQKUHjYOdirCAM", description: "Shazam! is a 2019 superhero film based on the DC Comics character Shazam!. Directed by David F. Sandberg and starring Chris Hemsworth, it is the second film in the Shazam! film series. The film premiered on May 1, 2019, and was released on May 1, 2019, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/shazam.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Joker", year: 2019, director: " Todd Phillips", rating: 8.4, trailer: "https://youtu.be/zAGVQLHvwOY?si=6OamdHwEA1IpfHk9", description: "Joker is a 2019 superhero film based on the DC Comics character Joker. Directed by Todd Phillips and starring Chris Hemsworth, it is the second film in the Joker film series. The film premiered on May 1, 2019, and was released on May 1, 2019, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/joker.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Birds of Prey", year: 2020, director: " Cathy Yan", rating: 6.1, trailer: "https://youtu.be/x3HbbzHK5Mc?si=sKGv15WLVJWNMg-5", description: "Birds of Prey is a 2020 superhero film based on the DC Comics character Birds of Prey. Directed by Cathy Yan and starring Chris Hemsworth, it is the second film in the Birds of Prey film series. The film premiered on May 1, 2020, and was released on May 1, 2020, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/Birdsofprey.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "The Suicide Squad", year: 2021, director: " James Wan", rating: 7.2, trailer: "https://youtu.be/Z1EbSXxrZ34?si=j7V9u06PFROv7ibl", description: "The Suicide Squad is a 2021 superhero film based on the DC Comics character The Suicide Squad. Directed by James Wan and starring Chris Hemsworth, it is the second film in the The Suicide Squad film series. The film premiered on May 1, 2021, and was released on May 1, 2021, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/SuicideSquad(2021).jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "The Batman", year: 2022, director: " Matt Reeves", rating: 7.8, trailer: "https://youtu.be/mqqft2x_Aa4?si=YgJCK4d3GFS5HiD0", description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption. Starring Robert Pattinson.", poster: "images/Batman(2022).jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Black Adam", year: 2022, director: " Patty Jenkins", rating: 6.2, trailer: "https://youtu.be/mkomfZHG5q4?si=kiIOZJGCAYz7ATOG", description: "Black Adam is a 2022 superhero film based on the DC Comics character Black Adam. Directed by Patty Jenkins and starring Chris Hemsworth, it is the second film in the Black Adam film series. The film premiered on May 1, 2022, and was released on May 1, 2022, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/blackadam.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "The Flash", year: 2023, director: " James Wan", rating: 6.7, trailer: "https://youtu.be/r51cYVZWKdY?si=-JpTon7MTDsAMA4O", description: "The Flash is a 2023 superhero film based on the DC Comics character The Flash. Directed by James Wan and starring Chris Hemsworth, it is the second film in the The Flash film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/theflash.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Blue Beetle", year: 2023, director: "David Ayer", rating: 5.9, trailer: "https://youtu.be/KQc6mkTgDXw?si=7Ymrjo7KALDv7uEV", description: "Blue Beetle is a 2023 superhero film based on the DC Comics character Blue Beetle. Directed by David Ayer and starring Chris Hemsworth, it is the second film in the Blue Beetle film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/bluebeetle.jpg", links: { "720p": "", "1080p": "", "4k": "" } },
    { title: "Aquaman and the Lost Kingdom", year: 2023, director: " James Wan", rating: 5.6, trailer: "https://youtu.be/vKaWnXbkh8s?si=37aBDBEUo-Tr4aK0", description: "Aquaman and the Lost Kingdom is a 2023 superhero film based on the DC Comics character Aquaman and the Lost Kingdom. Directed by James Wan and starring Chris Hemsworth, it is the second film in the Aquaman and the Lost Kingdom film series. The film premiered on May 1, 2023, and was released on May 1, 2023, in the United States. It was a critical and commercial success, grossing over $677 million worldwide. The film was well-received by critics, who praised its action sequences, humor, and performances. It was also well-received by fans, who praised its action sequences, humor, and performances.", poster: "images/aquamanandthelostkingdom.jpg", links: { "720p": "", "1080p": "", "4k": "" } }
];

const allMovies = [...marvelMovies, ...dcMovies];

// Global listener for download buttons
document.addEventListener('click', function (e) {
    // Check if clicked on a quality trigger button
    const triggerBtn = e.target.closest('.download-trigger-btn');
    if (triggerBtn) {
        const qualitySpan = triggerBtn.querySelector('.marvel-font');
        if (qualitySpan) {
            const qualityText = qualitySpan.innerText.trim().toLowerCase();
            const urlParams = new URLSearchParams(window.location.search);
            const titleParam = urlParams.get('title');

            if (titleParam) {
                // allMovies is defined in movies.js
                const movie = allMovies.find(m => m.title === titleParam);
                if (movie) {
                    const links = movie.links || {};
                    let key = '720p';
                    if (qualityText.includes('1080')) key = '1080p';
                    if (qualityText.includes('4k')) key = '4k';

                    if (!links[key] || links[key] === "") {
                        // Mark as missing but do NOT prevent modal from opening
                        window._selectedDownloadLink = "MISSING";
                    } else {
                        // Store actual link for the final button to use
                        window._selectedDownloadLink = links[key];
                    }
                }
            }
        }
    }

    // Check if clicked on the final download button inside modal
    const finalBtn = e.target.closest('#finalDownloadBtn');
    if (finalBtn && !finalBtn.disabled && window._selectedDownloadLink) {
        if (window._selectedDownloadLink === "MISSING") {
            // Prevent normal flow (Thank you modal) and show error instead
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();
            setTimeout(() => {
                alert('Sorry for inconvinience, that quality is not avilable yet. Please try downloading other Quality');
            }, 10);
            return false;
        } else {
            const link = window._selectedDownloadLink;

            // Check if linkConversion.js is loaded and handles it
            if (typeof handleTeraboxDownload === 'function') {
                const handled = handleTeraboxDownload(link, finalBtn, e);
                if (handled) return false;
            }

            // Valid link exists (non-Terabox or regular). Let the original alert show and modal close, then open link
            setTimeout(() => {
                window.open(window._selectedDownloadLink, '_blank');
                window._selectedDownloadLink = null;
            }, 100);
        }
    }
}, true); // Use capture phase to intercept before other handlers
